name: Storybook
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "stories/**"
      - ".storybook/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          yarn install --frozen-lockfile
          yarn build-docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: docs
          folder: storybook-static
